# This file is for reference only - not used in ECS deployment
# ECS will use individual container images from DockerHub

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    # Environment variables will be set in ECS Task Definition
    
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ""  # Will be set during ECS build
    ports:
      - "4173:4173"
    # No environment variables needed at runtime