services:
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"  
    env_file:
      - ./frontend/.env
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    restart: always